### ISSUE TITLE
TalksのIndexページに目次が欲しい

### ISSUE THREAD

**Issue by nissyi-gh** [kaigionrails/conference-app#81]
## 解決したいこと

<img width="280" alt="image" src="https://github.com/kaigionrails/conference-app/assets/81596063/cb5146cb-0fe0-4e27-b54d-f6d94309aad0">

Talksページにアクセスすると、初日の最初のトークが表示されます。2日目になると初日のトークより2日目のトークへのアクセスがしやすいと嬉しい気持ちです。手動でスクロールしなくても2日目のトークをシュッと表示できるように、目次を追加することを提案します。

**Comment by unasuke** [comment]
**WAKARU**
