### ISSUE TITLE
バッヂを登録できたことに対するフィードバックを表示したい

### ISSUE THREAD

**Issue by nissyi-gh** [kaigionrails/conference-app#82]
## 解決したいこと

|登録前|登録後|
|:-:|:-:|
|<img width="280" alt="image" src="https://github.com/kaigionrails/conference-app/assets/81596063/70b85e42-eaf2-4eac-ac51-c0c397776a7b">|<img width="280" alt="image" src="https://github.com/kaigionrails/conference-app/assets/81596063/ba1a9b00-134d-4c41-bc21-e8705ec8d549">|

バッヂを作成した後、登録が完了できたかどうかが「テキストがサンプルになること」でしか判断できません。フラッシュなどで「登録が完了しました」と表示されるとわかりやすくなる気がします。

**Comment by unasuke** [comment]
🤣 🤣 

https://github.com/kaigionrails/conference-app/blob/77a1a69eb317954b3977096e1a391a1a86bf7e86/app/controllers/profile_badges_controller.rb#L18-L25
